name: Android CI

on:
  push:
    tags: [ "v*.*.*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew :gelm:test
    - name: Build with Gradle
      run: ./gradlew publishingZipArchive
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
        path: ./gelm/build/distributions/
        # A glob pattern matching the artifacts that should be downloaded. Ignored if name is specified.
        pattern: deploy-*.zip
        # When multiple artifacts are matched, this changes the behavior of the destination directories. If true, the downloaded artifacts will be in the same directory specified by path. If false, the downloaded artifacts will be extracted into individual named directories within the specified path.
        merge-multiple: false
          
